### ISSUE TITLE
Maybe also add INT 15h services 86h and 83h

### ISSUE THREAD

**Issue by TzOk83** [640-KB/GLaTICK#2]
I believe these INT 15h services also rely on the RTC.

**Comment by 640-KB** [comment]
Yes, I do want to include `86h`, as well as `INT 15h / 83h`, `INT 1Ah / 6,7h` on cards that support/enable interrupts (which unfortunately is not the majority of them).  Thank you for the reminder - I'll make sure that is implemented.

**Comment by 640-KB** [comment]
> I believe these INT 15h services also rely on the RTC.

I looked into this a little further, and so far none of the RTCs I've been able to test support alarms/interrupts in the millisecond range so INT 15,83/86 won't end up being able to use RTC. However, AH=86 could still be done by latching and reading the PIT counters directly (I already do something very similar in GLaBIOS). AH=83 would be a bit more complicated without an RTC to support it, though could be done by reprogramming the PIT and intercepting INT 08h. 

Since it doesn't seem like it is actually going to be supported by the RTC, and would have not really ever been available for XT software to use anyway, I'm not sure it makes sense to include in this project.

Thanks for the suggestion though.  I would like to see it implemented someday!
