### ISSUE TITLE
Support Leading Edge Model D

### ISSUE THREAD

**Issue by evan** [640-KB/GLaTICK#3]
The Leading Edge Model D has a MM58167 RTC on port 300h. Is it possible to support this in GLaTICK?

**Comment by 640-KB** [comment]
Yep, if you wanted to build it yourself you can change it to any port (or ports) you like in [the code here](https://github.com/640-KB/GLaTICK/blob/1de12d2feab4484cb8ef9eea52c4119e00595ef6/src/RTC_NS.ASM#L137).  I just don't include `300H` by default to avoid possible conflicts or misdetection, since it can be used by a lot of other stuff (MIDI cards, XT-IDE, etc).

Anyway, here's a build of the MM58167 that includes port `300H`:
https://github.com/640-KB/GLaTICK/releases/download/v0.8.6/GLaTICK_0.8.6_NS_RP_300H.ROM

Let me know how that works!

640KB

**Comment by evan** [comment]
Thanks, I will. I am new at this, if you have any tips on how to use an XT-IDE to program an option rom chip (I think I need an AT28C64B?) to go in an Intel 8/16 NIC, I would appreciate it. 

The CLKDVR.SYS driver for the Leading Edge RTC has bugs with DOS > 3.1 so I am hoping this might be a solution.

**Comment by 640-KB** [comment]
Yeah, you'll just want to get some 8K 28C64 EEPROMs (Atmel, etc) -- if you are lucky, you might be able to find them on Mouser or Digikey (though they are usually out of stock), and I've just bought most of the ones I have on eBay.  I've never personally used the XT-IDE card to write them, but on the [XUB site](https://xtideuniversalbios.org/) under "Using XTIDECFG.COM (XTIDE Universal BIOS configuration and flashing program)" it says you can with the `XTIDECFG.COM` program by using the "Load BIOS from file" option, so it should absolutely work.

Which version of DOS are you planning to use?  Complete BIOS real-time clock support wasn't fully added to DOS until version 3.3, so as long as you are that or higher you should be good.  Have you tried any other clock software that's worked with the clock?  The MM58167 interface is pretty standardized (but I'm always finding new surprises!).

Keep me posted - haven't tested before on a Leading Edge, so should be interesting to hear how it goes.

**Comment by 640-KB** [comment]
> I think I need an AT28C64B?

Yep.  I believe the AT28C64 (no letters) should work as well if you find them easier too.

**Comment by evan** [comment]
I am using MS-DOS 6.22. The clock works fine, but in DOS 6 when the driver updates the DOS time, the year is not properly set, so it's always 1980.

There is no other MM58167 driver that expects port 300h, so my other option was to try disassembling something and changing it.

**Comment by 640-KB** [comment]
In the meantime, you can also try the "[David_M's clock reader](https://www.minuszerodegrees.net/rtc/rtc.htm)" (use `CLOCK D F5`) to see if the clock is more or less standard. It's not a clock driver, but it's a great little "swiss army knife" of clock tools that make it easy to verify if the clock chip is working right.  If it shows the right time (the year could be off by 20 years, but that's okay) then you'll know GLaTICK will definitely work with it.  If it doesn't work, GLaTICK may still work though.  Just something to try if you don't have any AT28C64, while you're waiting for them to arrive. :)

**Comment by evan** [comment]
I have ordered two EEPROMs. 

![IMG_6833](https://github.com/640-KB/GLaTICK/assets/210/91a8172c-fc35-49e4-ba1b-4cba4310ee79)

Leading Edge DOS 3.1 sees the correct year. CLOCK.COM sees the clock, but thinks it's 1980, just like DOS 6.22. The Leading Edge has Phoenix BIOS 3.0. Maybe there's some kind of offset or epoch that needs to be adjusted in DOS/CLOCK.COM?

**Comment by 640-KB** [comment]
> Leading Edge DOS 3.1 sees the correct year. CLOCK.COM sees the clock, but thinks it's 1980, just like DOS 6.22. The Leading Edge has Phoenix BIOS 3.0. Maybe there's some kind of offset or epoch that needs to be adjusted in DOS/CLOCK.COM?

That's actually fine - in fact what you are seeing is good, because it confirms that the Leading Edge has a totally standard 58167 hardware implementation.

There's actually no standard for how the 58167 stores the year in its registers (in fact it doesn't even *have* a year register), so it's up to the clock software for how it wants to handle it.  It's no big deal -- just means usually if you change clock software you'll have to reset the time once.  The first time you run GLaTICK, most likely it will say "ERROR" and reset the time back to 01-01-1980, and then you can set it in DOS once and you'll be good to go!
